import React, { useContext } from 'react';
import { Moon, X, Copy } from 'lucide-react';
import { ThemeContext } from '../../contexts/ThemeContext';

interface HandoffModalProps {
  isOpen: boolean;
  onClose: () => void;
  handoffContent: string;
  isLoading: boolean;
}

export const HandoffModal: React.FC<HandoffModalProps> = ({ isOpen, onClose, handoffContent, isLoading }) => {
  const { isDarkMode } = useContext(ThemeContext);

  if (!isOpen) return null;
  
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
      <div className={`w-full max-w-3xl rounded-xl shadow-2xl flex flex-col h-[80vh] ${isDarkMode ? 'bg-[#1e1e1e] border border-gray-700' : 'bg-white'}`}>
         <div className="flex items-center justify-between p-4 border-b border-gray-700/50">
            <div className="flex items-center gap-2">
               <Moon className="w-5 h-5 text-[#d97757]" />
               <h3 className={`font-bold text-lg ${isDarkMode ? 'text-white' : 'text-gray-900'}`}>Sign-Out / Handoff</h3>
            </div>
            <button onClick={onClose} className="p-1 hover:bg-gray-700/50 rounded text-gray-400">
                <X className="w-5 h-5" />
            </button>
         </div>

         <div className="flex-1 overflow-hidden p-0 relative">
            {isLoading ? (
              <div className="absolute inset-0 flex flex-col items-center justify-center gap-4">
                 <div className="w-8 h-8 border-2 border-[#d97757] border-t-transparent rounded-full animate-spin"></div>
                 <span className="text-gray-500 text-sm font-medium">Generating SBAR Handoff...</span>
              </div>
            ) : (
              <textarea 
                readOnly
                value={handoffContent}
                className={`w-full h-full resize-none font-mono text-sm p-6 focus:outline-none ${isDarkMode ? 'bg-[#151515] text-gray-300' : 'bg-gray-50 text-gray-900'}`}
              />
            )}
         </div>

         <div className="p-4 border-t border-gray-700/50 flex justify-between items-center bg-opacity-50 bg-black/10">
             <span className="text-xs text-gray-500">Generated by AI from current patient list. Verify before sending.</span>
             <button 
                onClick={() => navigator.clipboard.writeText(handoffContent)}
                disabled={isLoading}
                className="px-4 py-2 rounded-lg text-sm font-bold bg-[#d97757] text-white hover:bg-[#c66a4d] flex items-center gap-2 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
             >
                <Copy className="w-4 h-4" />
                Copy to Clipboard
             </button>
         </div>
      </div>
    </div>
  );
};
